# Generated by Django 5.2.14 on 2026-06-01 17:06

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcjonalne zdjęcie wyróżniające wpis (JPG, PNG, WEBP)', null=True, upload_to=blog.models.post_image_path, verbose_name='Zdjęcie główne'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Znaczek weryfikacji nadawany przez administratora', verbose_name='Zweryfikowany'),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('orange', 'Klasyczny pomarańczowy'), ('blue', 'Oceaniczny niebieski'), ('green', 'Leśna zieleń'), ('purple', 'Królewska purpura'), ('red', 'Płomienna czerwień'), ('teal', 'Morski turkus'), ('dark', 'Ciemny')], default='orange', help_text='Twój osobisty motyw kolorystyczny interfejsu', max_length=20, verbose_name='Motyw kolorystyczny'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500, verbose_name='Zajawka'),
        ),
    ]
